# https://taskfile.dev
version: '3'

vars:
  SVID_API_DIR: scenarios/05-svid-api

tasks:
  build:
    desc: Build all Go binaries
    deps: [build-dashboard, build-svid-server, build-svid-client]

  build-dashboard:
    desc: Build the SPIRE dashboard
    cmds:
      - go build -o dashboard/dashboard{{exeExt}} ./dashboard/
    sources:
      - "dashboard/**/*.go"
      - "dashboard/templates/*"
      - go.mod
      - go.sum
    generates:
      - "dashboard/dashboard{{exeExt}}"

  build-svid-server:
    desc: Build the SVID API server
    cmds:
      - go build -o {{.SVID_API_DIR}}/server/svid-server{{exeExt}} ./{{.SVID_API_DIR}}/server/
    sources:
      - "{{.SVID_API_DIR}}/server/**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.SVID_API_DIR}}/server/svid-server{{exeExt}}"

  build-svid-client:
    desc: Build the SVID API client
    cmds:
      - go build -o {{.SVID_API_DIR}}/client/svid-client{{exeExt}} ./{{.SVID_API_DIR}}/client/
    sources:
      - "{{.SVID_API_DIR}}/client/**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.SVID_API_DIR}}/client/svid-client{{exeExt}}"

  clean:
    desc: Remove all built binaries
    cmds:
      - cmd: rm -f dashboard/dashboard{{exeExt}}
        platforms: [linux, darwin]
      - cmd: rm -f {{.SVID_API_DIR}}/server/svid-server{{exeExt}}
        platforms: [linux, darwin]
      - cmd: rm -f {{.SVID_API_DIR}}/client/svid-client{{exeExt}}
        platforms: [linux, darwin]
      - cmd: if exist "dashboard\dashboard{{exeExt}}" del /f "dashboard\dashboard{{exeExt}}"
        platforms: [windows]
      - cmd: if exist "{{.SVID_API_DIR}}\server\svid-server{{exeExt}}" del /f "{{.SVID_API_DIR}}\server\svid-server{{exeExt}}"
        platforms: [windows]
      - cmd: if exist "{{.SVID_API_DIR}}\client\svid-client{{exeExt}}" del /f "{{.SVID_API_DIR}}\client\svid-client{{exeExt}}"
        platforms: [windows]

  lint:
    desc: Run Go linter
    cmds:
      - go vet ./...

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

# ---- maintenance tasks ----

  deps:
    desc: List direct dependencies with available updates
    silent: true
    cmds:
      - go mod tidy
      - go list -u -m -f "{{`{{if not .Indirect}}{{.}}{{end}}`}}" all
