# https://taskfile.dev
version: '3'

tasks:
  build:
    desc: Build all Go binaries
    deps: [build-dashboard, build-svid-server, build-svid-client, build-scenarios]

  build-dashboard:
    desc: Build the SPIRE dashboard
    cmds:
      - go build -o bin/dashboard{{exeExt}} ./cmd/dashboard/
    sources:
      - "cmd/dashboard/**/*.go"
      - "cmd/dashboard/templates/*"
      - go.mod
      - go.sum
    generates:
      - "bin/dashboard{{exeExt}}"

  build-svid-server:
    desc: Build the SVID API server
    cmds:
      - go build -o bin/svid-server{{exeExt}} ./cmd/svid-server/
    sources:
      - "cmd/svid-server/**/*.go"
      - go.mod
      - go.sum
    generates:
      - "bin/svid-server{{exeExt}}"

  build-svid-client:
    desc: Build the SVID API client
    cmds:
      - go build -o bin/svid-client{{exeExt}} ./cmd/svid-client/
    sources:
      - "cmd/svid-client/**/*.go"
      - go.mod
      - go.sum
    generates:
      - "bin/svid-client{{exeExt}}"

  build-scenarios:
    desc: Build all scenario binaries
    cmds:
      - go build -o bin/scenario-01-simple{{exeExt}} ./cmd/scenario-01-simple/
      - go build -o bin/scenario-02-dashboard{{exeExt}} ./cmd/scenario-02-dashboard/
      - go build -o bin/scenario-03-workload{{exeExt}} ./cmd/scenario-03-workload/
      - go build -o bin/scenario-04-tpm{{exeExt}} ./cmd/scenario-04-tpm/
      - go build -o bin/scenario-05-svid-api{{exeExt}} ./cmd/scenario-05-svid-api/
      - go build -o bin/scenario-06-metrics{{exeExt}} ./cmd/scenario-06-metrics/
      - go build -o bin/scenario-07-production{{exeExt}} ./cmd/scenario-07-production/
    sources:
      - "cmd/scenario-*/**/*.go"
      - "internal/**/*.go"
      - go.mod
      - go.sum
    generates:
      - "bin/scenario-01-simple{{exeExt}}"
      - "bin/scenario-02-dashboard{{exeExt}}"
      - "bin/scenario-03-workload{{exeExt}}"
      - "bin/scenario-04-tpm{{exeExt}}"
      - "bin/scenario-05-svid-api{{exeExt}}"
      - "bin/scenario-06-metrics{{exeExt}}"
      - "bin/scenario-07-production{{exeExt}}"

  clean:
    desc: Remove all built binaries
    cmds:
      - rm -f bin/*

  lint:
    desc: Run Go linter
    cmds:
      - go vet ./...

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

# ---- running stuff ----

  run-scenario-01-simple:
    desc: Run the simple scenario
    cmds:
      - go run ./cmd/scenario-01-simple/

# ---- maintenance tasks ----

  deps:
    desc: List direct dependencies with available updates
    silent: true
    cmds:
      - go list -u -m -f "{{`{{if not .Indirect}}{{.}}{{end}}`}}" all
