name: tornjak

services:
  spire-server:
    container_name: tornjak-spire-server
    image: ghcr.io/spiffe/spire-server:1.14.5
    hostname: spire-server
    volumes:
      - ./spire/server:/opt/spire/conf/server
      - spire-server-socket:/tmp/spire-server/private
    command: ["-config", "/opt/spire/conf/server/server.conf"]

  spire-agent:
    container_name: tornjak-spire-agent
    image: ghcr.io/spiffe/spire-agent:1.14.5
    hostname: spire-agent
    depends_on: ["spire-server"]
    volumes:
      - ./spire/agent:/opt/spire/conf/agent
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]

  tornjak-backend:
    container_name: tornjak-tornjak-backend
    image: ghcr.io/spiffe/tornjak-backend:latest
    hostname: tornjak-backend
    depends_on: ["spire-server"]
    volumes:
      - ./spire/server:/opt/spire/conf/server
      - ./tornjak:/run/tornjak
      - spire-server-socket:/tmp/spire-server/private
    command:
      - --spire-config
      - /opt/spire/conf/server/server.conf
      - --tornjak-config
      - /run/tornjak/tornjak.conf
    ports:
      - "10000:10000"

  tornjak-frontend:
    container_name: tornjak-tornjak-frontend
    image: ghcr.io/spiffe/tornjak-frontend:latest
    hostname: tornjak-frontend
    depends_on: ["tornjak-backend"]
    environment:
      - REACT_APP_API_SERVER_URI=http://localhost:10000
    ports:
      - "3000:3000"

volumes:
  spire-server-socket:
