agent {
    data_dir = "/opt/spire/data/agent"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/opt/spire/sockets/workload_api.sock"
    trust_domain = "mirmat.org"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "x509pop" {
        plugin_data {
            private_key_path = "/opt/spire/conf/agent/devid-key.pem"
            certificate_path = "/opt/spire/conf/agent/devid-cert.pem"
            intermediates_path = "/opt/spire/conf/agent/devid-ca.pem"
        }
    }
    KeyManager "memory" {
        plugin_data = {}
    }
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}

telemetry {
    Prometheus {
        host = "spire-agent-2"
        port = 8090
    }
    Statsd = [
        {
            address = "graphite-statsd:8125"
        },
    ]
}
