name: workload

services:
  spire-server:
    container_name: workload-spire-server
    image: ghcr.io/spiffe/spire-server:1.15.0
    hostname: spire-server
    volumes:
      - ./spire/server:/opt/spire/conf/server
      - spire-server-socket:/tmp/spire-server/private
    command: ["-config", "/opt/spire/conf/server/server.conf"]
  spire-agent:
    container_name: workload-spire-agent
    image: ghcr.io/spiffe/spire-agent:1.15.0
    hostname: spire-agent
    depends_on: ["spire-server"]
    volumes:
      - ./spire/agent:/opt/spire/conf/agent
      - shared-socket:/opt/spire/sockets
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]
  dashboard:
    container_name: workload-dashboard
    image: spiffe-spire-demo-dashboard:local
    build:
      context: ../..
      dockerfile: dashboard/Containerfile
    hostname: dashboard
    depends_on: ["spire-server"]
    volumes:
      - spire-server-socket:/tmp/spire-server/private
    ports:
      - "8080:8080"
  workload:
    container_name: workload-workload
    image: ghcr.io/spiffe/spire-agent:1.15.0
    hostname: workload
    depends_on: ["spire-agent"]
    pid: "container:workload-spire-agent"
    volumes:
      - shared-socket:/opt/spire/sockets
    entrypoint: ["/opt/spire/bin/spire-agent", "api", "watch", "-socketPath", "/opt/spire/sockets/workload_api.sock"]

volumes:
  shared-socket:
  spire-server-socket:
