name: tpm

services:
  spire-server:
    container_name: tpm-spire-server
    image: ghcr.io/spiffe/spire-server:1.14.5
    hostname: spire-server
    volumes:
      - ./spire/server:/opt/spire/conf/server
    command: ["-config", "/opt/spire/conf/server/server.conf"]

  spire-agent:
    container_name: tpm-spire-agent
    image: ghcr.io/spiffe/spire-agent:1.14.5
    hostname: spire-agent
    depends_on: ["spire-server"]
    volumes:
      - ./spire/agent:/opt/spire/conf/agent
      - /var/run/:/var/run/
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]
