services:
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.14.5
    hostname: spire-server
    volumes:
      - ./spire/server:/opt/spire/conf/server
    command: ["-config", "/opt/spire/conf/server/server.conf"]

  spire-agent:
    image: ghcr.io/spiffe/spire-agent:1.14.5
    hostname: spire-agent
    depends_on: ["spire-server"]
    volumes:
      - ./spire/agent:/opt/spire/conf/agent
      - workload-socket:/opt/spire/sockets
    command: ["-config", "/opt/spire/conf/agent/agent.conf", "-joinToken", "${SPIRE_AGENT_JOIN_TOKEN}"]

  svid-server:
    image: spiffe-spire-demo-svid-server:local
    build:
      context: ../..
      dockerfile: scenarios/04-svid-api/server/Containerfile
    hostname: svid-server
    depends_on: ["spire-agent"]
    volumes:
      - workload-socket:/opt/spire/sockets
    environment:
      - PORT=8443

  svid-client:
    image: spiffe-spire-demo-svid-client:local
    build:
      context: ../..
      dockerfile: scenarios/04-svid-api/client/Containerfile
    hostname: svid-client
    depends_on: ["svid-server"]
    volumes:
      - workload-socket:/opt/spire/sockets
    environment:
      - SERVER_URL=https://svid-server:8443

volumes:
  workload-socket:
